# gid_tools/envs/feedback.py
"""
Environment for computing reward feedback on images generated by a diffusion model.
"""
import torch
import torch.nn as nn
import numpy as np
from pathlib import Path
from typing import Callable, Dict, Optional, Union
from gid_tools.envs.training_functions.classifier.cnn import ToolCNN
import configparser
import torch.nn.functional as F



_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
_model = None

def _get_cnn():
    global _modelx
    if _model is None:
        # new: point to top‐level checkpoints/
        this_dir = Path(__file__).resolve().parent            # .../envs
        classifier_dir = this_dir / "training_functions" / "classifier"

        # read model_output from its config
        cfg = configparser.ConfigParser()
        cfg.read(classifier_dir / "config_cnn.ini")
        model_rel = cfg["paths"]["model_output"]               # "checkpoints/model.pth"
        _checkpoint = (classifier_dir / model_rel).resolve()
 
        if not _checkpoint.exists():
            raise FileNotFoundError(
                f"CNN checkpoint not found at {_checkpoint}. Please run the training script first."
            )
        _cnn = ToolCNN(num_classes=5).to(_device)
        _cnn.load_state_dict(torch.load(str(_checkpoint), map_location=_device))
        _cnn.eval()
        _model = _cnn
    
    return _model

def pixel_area_tensor(img: torch.Tensor, threshold: float = 0.0) -> int:
    """
    Compute the 2D area (number of 'on' pixels) of a Torch image in [-1,1].
    Assumes img.shape = [1,H,W] or [H,W].
    Counts pixels > threshold.
    """
    # squeeze channel if present
    if img.dim() == 3:
        img = img.squeeze(0)
    mask = img > threshold
    
    reward = int(mask.sum().item())
    
    # normalise by dividing by number of pixels
    reward = reward / (img.shape[0] * img.shape[1]) 
    # reward = np.exp(reward / (img.shape[0] * img.shape[1])) # exponentiate reward
    
    
    return reward 

def cnn_prob_reward(img: torch.Tensor, **kwargs) -> float:
    """
    Reward = P(class 0) if predicted class == 0, else 0.
    P(class 0) is the softmax-normalized score for class 0.
    Expects `img` in the same format you trained on: [1,H,W], values in [-1,1].
    """
    # ensure correct shape: [1,1,H,W] and ignore any extra kwargs
    if img.dim() == 2:
        img = img.unsqueeze(0)
    x = img.unsqueeze(0).to(_device)  # batch dim → [1,1,H,W]
    
    cnn = _get_cnn()  
    
    with torch.no_grad():
        logits = cnn(x)               # → [1, num_classes]
        probs  = F.softmax(logits, dim=1)
        p0     = probs[0, 0].item()
        pred   = logits.argmax(dim=1).item()
    return p0 if pred == 4 else 0.0

def cnn_cross_ent_loss(img: torch.Tensor, label: int, cnn: nn.Module) -> torch.Tensor:
    logits = cnn(img.unsqueeze(0))        # img: [1, C, H, W]
    target = torch.tensor([label], device=logits.device)
    return torch.nn.functional.cross_entropy(logits, target)


class ToolRewardEnv:
    """
    ToolRewardEnv applies reward functions to images generated by a diffusion model.

    Methods
    -------
    - register_reward(name, fn): register a custom reward function
    - compute(img, method=None, **kwargs): compute reward using the specified method
    """
    def __init__(self, default_method: str = 'pixel_area'):
        # registry of reward functions
        self._rewards: Dict[str, Callable[..., Union[int, float]]] = {}
        # register built-in methods
        self.register_reward('pixel_area', pixel_area_tensor)
        # set default
        self.register_reward('cnn_prob', cnn_prob_reward)
        self.default_method = default_method

    def register_reward(self, name: str, fn: Callable[..., Union[int, float]]):
        """
        Register a new reward function.

        Parameters
        ----------
        name : str
            Name of the reward function.
        fn : callable
            Function that takes (img: torch.Tensor, **kwargs) and returns a numeric reward.
        """
        if not callable(fn):
            raise ValueError(f"Reward function for '{name}' must be callable.")
        self._rewards[name] = fn

    def list_methods(self) -> list:
        """
        List all registered reward methods.
        """
        return list(self._rewards.keys())

    def compute(self, img: torch.Tensor, method: Optional[str] = None, **kwargs) -> Union[int, float]:
        """
        Compute the reward for a given image using the specified method.

        Parameters
        ----------
        img : torch.Tensor
            Image tensor from the diffusion model.
        method : str, optional
            The name of the reward function to use. Defaults to None, which uses the default method.
        **kwargs
            Additional arguments to pass to the reward function.

        Returns
        -------
        int or float
            The computed reward.
        """
        if method is None:
            method = self.default_method
        if method not in self._rewards:
            raise KeyError(f"Reward method '{method}' not found. Available methods: {self.list_methods()}")
        fn = self._rewards[method]
        return fn(img, **kwargs)
