[meta]
config_name = config.ini

[samples]
directory = samples
train_tensor_file = train_samples.pt
test_tensor_file  = test_samples.pt

[features]
directory = features

[rewards]
file = rewards.json

[generator]
batch_size = 100

[evaluate]
method = pixel_area
threshold = 0.0

[feature_extraction]
# Any options for this step

[train_reward_model]
num_epochs = 25
batch_size = 32
lr = 1e-3
