[meta]
config_name = config_ground_truth.ini

[samples]
directory = ground_truth_samples
tensor_file = samples.pt

[features]
directory = features_ground_truth

[rewards]
file = rewards_ground_truth.json

[generator]
batch_size = 100  # can still be used if needed

[evaluate]
# evaluate settings for ground-truth

[feature_extraction]
# feature settings for ground-truth

[train_reward_model]
num_epochs = 15
batch_size = 32
lr = 1e-3
