[meta]
config_name = config.ini

[samples]
directory = samples
train_tensor_file = train_samples.pt
test_tensor_file  = test_samples.pt

[features]
directory = features

[rewards]
file = rewards.json

[generator]
batch_size = 10

[evaluate]
method = pixel_area
threshold = 0.0

[feature_extraction]
# Any options for this step

[train_reward_model]
num_epochs = 30
batch_size = 32
lr = 1e-3

[fine_tune]
; SGD lr for the diffusion net
lr_diff = 1e-4
; LR for the reward MLP
lr_rew  = 1e-3

output_directory = greedy_outputs
batch_size = 10
num_iters  = 10
reward_epochs = 40
save_interval = 5
