[meta]
config_name = config.ini

[samples]
directory = samples
tensor_file = samples.pt

[features]
directory = features

[rewards]
file = rewards.json

[generator]
batch_size = 100

[evaluate]
# Add evaluate-specific settings here if needed

[feature_extraction]
# Any options for this step

[train_reward_model]
num_epochs = 15
batch_size = 32
lr = 1e-3
